const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const nodes=new Map();
const node=()=>({innerHTML:'',textContent:'',handlers:{},addEventListener(k,f){this.handlers[k]=f;},setAttribute(k,v){this[k]=v;}});
const $=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);};
const filters=['all','llm_exposure','cipher_compute','decrypt_auth','document_exposure','llm_bypass','other'].map(type=>Object.assign(node(),{dataset:{auditType:type}}));
$('auditFilters').querySelectorAll=()=>filters;
const events=Array.from({length:19},(_,i)=>({type:i===0?'new_type':'llm_exposure',no_plaintext:true,ts:'2026-09-28T12:00:00',fields:['<unsafe>'],field_count:1}));
const context={window:{}};vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../client/webui/static/settings-ui.js'),'utf8'),context);
const ui=context.window.ClawSettingsUI.create({$,esc:v=>String(v).replaceAll('<','&lt;'),api:async()=>({events,summary:{total_events:250},chain:{ok:false,reason:'<broken>'}})});
(async()=>{
 await ui.renderAuditTab();
 assert($('modalBody').innerHTML.indexOf('auditExportBtn')<$('modalBody').innerHTML.indexOf('auditEvents'));
 assert($('modalBody').innerHTML.includes('审计链需要复核'));
 assert($('modalBody').innerHTML.includes('&lt;broken>'));
 assert($('modalBody').innerHTML.includes('最近 200 条'));
 assert.equal(($('auditEvents').innerHTML.match(/class="audit-event"/g)||[]).length,8);
 assert(!$('auditEvents').innerHTML.includes('<unsafe>'));
 assert($('auditPrev').disabled);
 $('auditNext').handlers.click();$('auditNext').handlers.click();
 assert($('auditPageInfo').textContent.includes('第 3 / 3 页'));
 assert($('auditNext').disabled);
 filters.find(f=>f.dataset.auditType==='other').handlers.click();
 assert($('auditEvents').innerHTML.includes('new_type'));
 assert($('auditPageInfo').textContent.includes('第 1 / 1 页'));
 filters.find(f=>f.dataset.auditType==='decrypt_auth').handlers.click();
 assert($('auditEvents').innerHTML.includes('暂无记录'));
 assert($('auditNext').disabled && $('auditPrev').disabled);
 console.log('Audit paging checks passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
