/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "client.go"

#include<stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void _init_sk(GoString skFilePath);
extern __declspec(dllexport) void FreeDoublePtr(double* ptr);
extern __declspec(dllexport) void FreeIntPtr(int* ptr);
extern __declspec(dllexport) void FreeBoolPtr(_Bool* ptr);

// 加密标量float64
//
extern __declspec(dllexport) double* Encode(double input);

// 解密标量密文
//
extern __declspec(dllexport) double Decode(double* input, int clength);

// 加密向量float64
//
extern __declspec(dllexport) double* EncodeArray(double* input, int clength);

// 解密向量密文
//
extern __declspec(dllexport) double* DecodeArray(double* input, int clength);

// 解密二维float64数组
//
extern __declspec(dllexport) double* Encode2DArray(double* input, int length1, int length2);

// 解密二维密文数组
//
extern __declspec(dllexport) double* DecodeCipherFloat2dArray(double* input, int length1, int length2);

// 加密离散数组float64
//
extern __declspec(dllexport) double* EncodeDiscreteArray(double* input, int clength);

// 解密离散密文数组
//
extern __declspec(dllexport) double* DecodeDiscreteArray(double* input, int clength);

// tensor的加解密函数 将fp32的tensor加密为fp64的密文， 将fp64的密文解密为fp32的tensor
//
extern __declspec(dllexport) double* EncryptFloat32ArrayToCipherFloat(float* input, long long int length);
extern __declspec(dllexport) float* DecryptCipherFloatToFloat32Array(double* input, long long int length);

// 根据密文类型执行相应的加解密
//
extern __declspec(dllexport) double* EncryptDoubleArrayWithCate(double* input, int clength);
extern __declspec(dllexport) double* EncryptIntArrayWithCate(int* input, int clength);
extern __declspec(dllexport) double* EncryptBoolArrayWithCate(_Bool* input, int clength);
extern __declspec(dllexport) double* EncryptStringWithCate(int* data, int length);
extern __declspec(dllexport) double* DecryptCipherFloatWithCateFP64(double* data, int length);
extern __declspec(dllexport) int* DecryptCipherFloatWithCateInt(double* data, int length);
extern __declspec(dllexport) _Bool* DecryptCipherFloatWithCateBool(double* data, int length);
extern __declspec(dllexport) int* DecryptCipherFloatWithCateStr(double* data, int length);

#ifdef __cplusplus
}
#endif
