/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "export_float.go"
 #include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void _init_dict(GoString dictFilePath, GoString userFilePath);
extern void FreeMemory(double* ptr);
extern void FreeIntPtr(int* ptr);
extern void FreeBoolPtr(_Bool* ptr);
extern void arrtest1(double* arr, int clength);
extern void arrtest2(double* arr1, double* arr2, int clength);
extern double* GetEmptyCipherFloatArray();
extern double* GetEmptyCipherFloat();
extern double* AddCipherFloat(double* arr1, double* arr2, int clength);
extern double* AddCipherFloatDouble(double* arr, int clength, double m);
extern double* SubCipherFloat(double* arr1, double* arr2, int clength);
extern double* SubCipherFloatDouble(double* arr, int clength, GoFloat64 m);
extern double* SubCipherFloatDoubleRight(double* arr, int clength, GoFloat64 m);
extern double* MulCipherFloat(double* arr1, double* arr2, int clength);
extern double* MulCipherFloatDouble(double* arr1, int clength, double m);
extern double* DivCipherFloat(double* arr1, double* arr2, int clength);
extern double* DivCipherFloatDouble(double* arr1, int clength, double m);
extern double* DivCipherFloatDoubleRight(double* arr, int clength, GoFloat64 m);
extern double* InversCipherFloat(double* arr1, double* arr2, int clength);
extern int Compare2CipherFloat(double* arr1, double* arr2, int clength);
extern double* AddCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* AddCipherFloatArrayDouble(double* arr, int clength, GoFloat64 m);
extern double* AddCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* AddCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SubCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* SubCipherFloatArrayDouble(double* arr, int clength, GoFloat64 m);
extern double* SubCipherFloatArrayDoubleRight(double* arr, int clength, GoFloat64 m);
extern double* SubCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SubCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SubCipherFloatArrayArrayDoubleRight(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* MulCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* MulCipherFloatArrayDouble(double* arr1, int clength, double m);
extern double* MulCipherFloatArrayDoubleArray(double* arr1, int clength1, double* arr2, int clength2);
extern double* MulCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* MulCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* DivCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* DivCipherFloatArrayDouble(double* arr1, int clength, double m);
extern double* DivCipherFloatArrayDoubleRight(double* arr, int clength, double m);
extern double* DivCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* DivCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* DivCipherFloatArrayArrayDoubleRight(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* InversCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* ABSCipherFloat(double* arr, int clength);
extern double* ABSCipherFloatArray(double* arr, int clength);
extern double* ABSCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* PowCipherFloat(double* arr, int clength, int n);
extern double* PowCipherFloatArray(double* arr, int clength, int n);
extern double* PowCipherFloatArrayArray(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern double* PowCipherFloat_FractionOrder(double* arr, int clength, int n, int m);
extern double* PowCipherFloatArray_FractionOrder(double* arr, int clength, int n, int m);
extern double* PowCipherFloatArrayArray_FractionOrder(double* arr, int clength1, int clength2, int n, int m, int encryptType, int outputEncryptType, _Bool parallel);
extern int* Compare2CipherFloatArray(double* arr1, double* arr2, int clength);
extern int* Compare2CipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern _Bool EqualCipherFloat(double* arr1, double* arr2, int clength);
extern _Bool EqualCipherFloatDouble(double* arr, int clength, double m);
extern _Bool* EqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern _Bool* EqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern _Bool* EqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern _Bool* EqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern _Bool NotEqualCipherFloat(double* arr1, double* arr2, int clength);
extern _Bool NotEqualCipherFloatDouble(double* arr, int clength, double m);
extern _Bool* NotEqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern _Bool* NotEqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern _Bool* NotEqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern _Bool* NotEqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern _Bool GreaterEqualCipherFloat(double* arr1, double* arr2, int clength);
extern _Bool GreaterEqualCipherFloatDouble(double* arr, int clength, double m);
extern _Bool* GreaterEqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern _Bool* GreaterEqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern _Bool* GreaterEqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern _Bool* GreaterEqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern _Bool LessEqualCipherFloat(double* arr1, double* arr2, int clength);
extern _Bool LessEqualCipherFloatDouble(double* arr, int clength, double m);
extern _Bool* LessEqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern _Bool* LessEqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern _Bool* LessEqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern _Bool* LessEqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern _Bool GreaterCipherFloat(double* arr1, double* arr2, int clength);
extern _Bool GreaterCipherFloatDouble(double* arr, int clength, double m);
extern _Bool* GreaterCipherFloatArray(double* arr1, double* arr2, int clength);
extern _Bool* GreaterCipherFloatArrayDouble(double* arr, int clength, double m);
extern _Bool* GreaterCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern _Bool* GreaterCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern _Bool LessCipherFloat(double* arr1, double* arr2, int clength);
extern _Bool LessCipherFloatDouble(double* arr, int clength, double m);
extern _Bool* LessCipherFloatArray(double* arr1, double* arr2, int clength);
extern _Bool* LessCipherFloatArrayDouble(double* arr, int clength, double m);
extern _Bool* LessCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern _Bool* LessCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern double* SqrtCipherFloat(double* arr1, int clength);
extern double* SqrtCipherFloatArray(double* arr, int clength);
extern double* SqrtCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* HypotFloat(double* arr1, double* arr2, int clength);
extern double* HypotFloatArray(double* arr1, double* arr2, int clength);
extern double* HypotCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* Arctan2Float(double* arr1, double* arr2, int clength);
extern double* Arctan2CipherFloatArray(double* arr1, double* arr2, int clength);
extern double* Arctan2CipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* Rad2degFloat(double* arr, int clength);
extern double* Rad2degFloatArray(double* arr, int clength);
extern double* Rad2degCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* Deg2radFloat(double* arr, int clength);
extern double* Deg2radFloatArray(double* arr, int clength);
extern double* Deg2radCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* DegreesFloat(double* arr, int clength);
extern double* DegreesFloatArray(double* arr, int clength);
extern double* DegreesCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* RadiansFloat(double* arr, int clength);
extern double* RadiansFloatArray(double* arr, int clength);
extern double* RadiansCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* RoundCipherFloat(double* arr, int clength, int n, int m);
extern double* RoundCipherFloatArray(double* arr, int clength, int n, int m);
extern double* RoundCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryType, int n, int m, _Bool parallel);
extern double* RoundingNCipherFloat(double* arr, int clength, int n);
extern double* RoundingNCipherFloatArray(double* arr, int clength, int n);
extern double* RoundingNCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, int n, _Bool parallel);
extern double* ReciprocalFloat(double* arr, int clength);
extern double* ReciprocalFloatArray(double* arr, int clength);
extern double* ReciprocalFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* PositiveFloat(double* arr, int clength);
extern double* PositiveFloatArray(double* arr, int clength);
extern double* PositiveFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* NegativeFloat(double* arr, int clength);
extern double* NegativeFloatArray(double* arr, int clength);
extern double* NegativeFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CbrtFloat(double* arr, int clength);
extern double* CbrtCipherFloatArray(double* arr, int clength);
extern double* CbrtCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SquareFloat(double* arr, int clength);
extern double* SquareFloatArray(double* arr, int clength);
extern double* SquareFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* HeavisideFloat(double* arr1, double* arr2, int clength);
extern double* HeavisideCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* HeavisideCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SinCipherFloat(double* arr, int clength);
extern double* SinCipherFloatArray(double* arr, int clength);
extern double* SinCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CosCipherFloat(double* arr, int clength);
extern double* CosCipherFloatArray(double* arr, int clength);
extern double* CosCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CosineCipherFloatDiscreteArray(double* arr1, double* arr2, int clength);
extern double* TanCipherFloat(double* arr, int clength);
extern double* TanCipherFloatArray(double* arr, int clength);
extern double* TanCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ArcsinCipherFloat(double* arr, int clength);
extern double* ArcsinCipherFloatArray(double* arr, int clength);
extern double* ArcsinCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ArccosCipherFloat(double* arr, int clength);
extern double* ArccosCipherFloatArray(double* arr, int clength);
extern double* ArccosCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ArctanCipherFloat(double* arr, int clength);
extern double* ArctanCipherFloatArray(double* arr, int clength);
extern double* ArctanCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SinhCipherFloat(double* arr, int clength);
extern double* SinhCipherFloatArray(double* arr, int clength);
extern double* SinhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CoshCipherFloat(double* arr, int clength);
extern double* CoshCipherFloatArray(double* arr, int clength);
extern double* CoshCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* TanhCipherFloat(double* arr, int clength);
extern double* TanhCipherFloatArray(double* arr, int clength);
extern double* TanhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ArcsinhCipherFloat(double* arr, int clength);
extern double* ArcsinhCipherFloatArray(double* arr, int clength);
extern double* ArcsinhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ArccoshCipherFloat(double* arr, int clength);
extern double* ArccoshCipherFloatArray(double* arr, int clength);
extern double* ArccoshCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ArctanhCipherFloat(double* arr, int clength);
extern double* ArctanhCipherFloatArray(double* arr, int clength);
extern double* ArctanhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SumFloatArray(double* arr, int clength);
extern double* SumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* SumCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* SumCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanSumFloatArray(double* arr, int clength);
extern double* NanSumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* NanSumFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType);
extern double* NanSumFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType);
extern double* Unwrap(double* arr, int clength, double discont, double period);
extern double* UnwrapCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double discont, double period, _Bool parallel);
extern double* UnwrapCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double discont, double period, _Bool parallel);
extern double* FixCipherFloat(double* arr, int clength);
extern double* FixCipherFloatArray(double* arr, int clength);
extern double* FixCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* FloorCipherFloat(double* arr, int clength);
extern double* FloorCipherFloatArray(double* arr, int clength);
extern double* FloorCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CeilCipherFloat(double* arr, int clength);
extern double* CeilCipherFloatArray(double* arr, int clength);
extern double* CeilCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* DecimalCipherFloat(double* arr, int clength);
extern double* DecimalCipherFloatArray(double* arr, int clength);
extern double* DecimalCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ProdCipherArray(double* arr, int clength);
extern double* ProdCipherArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* ProdCipherArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* ProdCipherArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanProdCipherArray(double* arr, int clength);
extern double* NanProdCipherArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* NanProdCipherArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanProdCipherArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* CumProdCipherFloatArray(double* arr, int clength);
extern double* CumProdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern double* CumProdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* CumProdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* NanCumProdCipherFloatArray(double* arr, int clength);
extern double* NanCumProdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern double* NanCumProdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* NanCumProdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* CumSumCipherFloatArray(double* arr, int clength);
extern double* CumSumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern double* CumSumCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* CumSumCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* NanCumSumCipherFloatArray(double* arr, int clength);
extern double* NanCumSumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern double* NanCumSumCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* NanCumSumCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* DiffCipherFloatArray(double* arr, int clength, int n);
extern double* DiffCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern double* DiffCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern double* Ediff1dCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType);
extern double* GradientCipherFloatArray(double* arr, int clength);
extern double* GradientCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* GradientCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* GradientCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CrossCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2);
extern double* CrossCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int axis1, int axis2, int encryptType, int outputEncryptType);
extern double* TrapzCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* TrapzCipherFloatArrayDx(double* arr, int clength, double dx);
extern double* TrapzCipherFloatArrayArrayAxis0(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* TrapzCipherFloatArrayArrayAxis1(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* TrapzCipherFloatArrayArrayDxAxis0(double* arr, int clength1, int clength2, int encryptType, double dx, _Bool parallel);
extern double* TrapzCipherFloatArrayArrayDxAxis1(double* arr, int clength1, int clength2, int encryptType, double dx, _Bool parallel);
extern double* NormNCipherFloatArray(double* arr, int clength, int n);
extern double* NormPosInfCipherFloatArray(double* arr, int clength);
extern double* NormNegInfCipherFloatArray(double* arr, int clength);
extern int NormZeroCipherFloatArray(double* arr, int clength);
extern double* MinCipherFloatArray(double* arr, int clength);
extern double* MinCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MinCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MinCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MaxCipherFloatArray(double* arr, int clength);
extern double* MaxCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MaxCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MaxCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MeanCipherFloatArray(double* arr, int clength);
extern double* MeanCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MeanCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MeanCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanMeanCipherFloatArray(double* arr, int clength);
extern double* NanMeanCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanMeanCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanMeanCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int ArgMinCipherFloatArray(double* arr, int clength);
extern int ArgMinCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int* ArgMinCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int* ArgMinCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int ArgMaxCipherFloatArray(double* arr, int clength);
extern int ArgMaxCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int* ArgMaxCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int* ArgMaxCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* OnesCipherFloat();
extern double* OnesCipherFloatArray(int n);
extern double* OnesCipherFloatArrayArray(int m, int n, int outputEncryptType);
extern double* ZerosCipherFloat();
extern double* ZerosCipherFloatArray(int n);
extern double* ZerosCipherFloatArrayArray(int m, int n, int outputEncryptType);
extern double* PlainArrayToCipherFloatArray(double* arr, int clength);
extern double* Plain2DArrayToCipherFloat2DArray(double* arr, int clength1, int clength2, int outputEncryptType);
extern double* LogCipherFloat(double* arr, int clength);
extern double* LogCipherFloatArray(double* arr, int clength);
extern double* LogCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* Log10CipherFloat(double* arr, int clength);
extern double* Log10CipherFloatArray(double* arr, int clength);
extern double* Log10CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* Log2CipherFloat(double* arr, int clength);
extern double* Log2CipherFloatArray(double* arr, int clength);
extern double* Log2CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ExpCipherFloat(double* arr, int clength);
extern double* ExpCipherFloatArray(double* arr, int clength);
extern double* ExpCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* Expm1CipherFloat(double* arr, int clength);
extern double* Expm1CipherFloatArray(double* arr, int clength);
extern double* Expm1CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* Exp2CipherFloat(double* arr, int clength);
extern double* Exp2CipherFloatArray(double* arr, int clength);
extern double* Exp2CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CipherFloatArrayAppendCipherFloat(double* arr, int clength1, double* c, int clength2);
extern double* CipherFloatArrayAppendCipherFloatArray(double* arr1, int clength1, double* arr2, int clength2);
extern double* CipherFloatArrayAppendCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern double* CipherFloatArrayArrayAppendCipherFloat(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern double* CipherFloatArrayArrayAppendCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern double* CipherFloatArrayArrayAppendCipherFloatArrayArrayAxisNone(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern double* CipherFloatArrayArrayAppendCipherFloatArrayArrayAxis0(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CipherFloatArrayArrayAppendCipherFloatArrayArrayAxis1(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* FloorDivideCipherFloat(double* arr1, double* arr2, int clength);
extern double* FloorDivideCipherFloatDouble(double* arr, int clength, double m);
extern double* FloorDivideCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* FloorDivideCipherFloatArrayDouble(double* arr, int clength, double m);
extern double* FloorDivideCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* FloorDivideCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern double* FModCipherFloat(double* arr1, double* arr2, int clength);
extern double* FModCipherFloatDouble(double* arr, int clength, GoFloat64 m);
extern double* FModCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* FModCipherFloatArrayDouble(double* arr, int clength, double m);
extern double* FModCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* FModCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern double* ModCipherFloat(double* arr1, double* arr2, int clength);
extern double* ModCipherFloatDouble(double* arr, int clength, double m);
extern double* ModCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* ModCipherFloatArrayDouble(double* arr, int clength, double m);
extern double* ModCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ModCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern double* ConvolveCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2);
extern double* ConvolveCipherFloatArraySame(double* arr1, double* arr2, int clength1, int clength2);
extern double* ConvolveCipherFloatArrayValid(double* arr1, double* arr2, int clength1, int clength2);
extern double* ClipCipherFloat(double* arr1, double* arr2, double* arr3, int clength);
extern double* ClipCipherFloatArray(double* arr1, double* arr2, double* arr3, int clength);
extern double* ClipCipherFloatArrayArray(double* arr1, double* arr2, double* arr3, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* SignCipherFloat(double* arr, int clength);
extern double* SignCipherFloatArray(double* arr, int clength);
extern double* SignCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* MaximumCipherFloat(double* arr1, double* arr2, int clength);
extern double* MaximumCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* MaximumCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* MinimumCipherFloat(double* arr1, double* arr2, int clength);
extern double* MinimumCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* MinimumCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* FMaxCipherFloat(double* arr1, double* arr2, int clength);
extern double* FMaxCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* FMaxCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* FMinCipherFloat(double* arr1, double* arr2, int clength);
extern double* FMinCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* FMinCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* ModFCipherFloat(double* arr, int clength);
extern double* ModFCipherFloatArray(double* arr, int clength);
extern double* ModFCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* DivModCipherFloat(double* arr1, double* arr2, int clength);
extern double* DivModCipherFloatDouble(double* arr, int clength, double m);
extern double* DivModCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* DivModCipherFloatArrayDouble(double* arr, int clength, double m);
extern double* DivModCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* DivModCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern double* InterpCipherFloat(double* c1, double* xp, double* fp, double* left, double* right, int clength1, int clength2);
extern double* InterpCipherFloatArray(double* c1, double* xp, double* fp, double* left, double* right, int clength1, int clength2, int clength3);
extern double* InterpCipherFloatArrayArray(double* c1, double* xp, double* fp, double* left, double* right, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* NanToNumCipherFloat(double* arr, double* nan, double* posinf, double* neginf, int clength);
extern double* NanToNumCipherFloatArray(double* arr, int clength1, double* nan, double* posinf, double* neginf, int clength2);
extern double* NanToNumCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double* nan, double* posinf, double* neginf, int clength3);
extern double* DotCipherFloatArray2DWith1D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern double* InnerCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* InnerCipherFloat2DWith1D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern double* InnerCipherFloat2DWith2D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* OuterCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int outputEncryptType, _Bool parallel);
extern double* MatmulCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* MatmulCipherFloatArrayFastCol(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* MatMulCipherFloat1DWith2D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType);
extern double* MatMulCipherFloat2DWith1D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, int outputEncryptType, _Bool parallel);
extern double* MatrixPowerCipherFloatArray(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern double* GetEyeCipherFloatArrayArray(int n, int outputEncryptType);
extern double* KronCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* TraceCipherFloatArray(double* arr, int clength1, int clength2, int encrytType, _Bool parallel);
extern double* DetCipherFloatArrayArray(double* arr, int clength1, int clength2, int encrytType);
extern double* NanminCipherFloatArray(double* arr, int clength);
extern double* NanminCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanminCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanminCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanmaxCipherFloatArray(double* arr, int clength);
extern double* NanmaxCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanmaxCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanmaxCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* PtpCipherFloatArray(double* arr, int clength);
extern double* PtpCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* PtpCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* PtpCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* PercentileCipherFloatArray(double* arr, int clength, double q);
extern double* PercentileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* PercentileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* PercentileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* NanPercentileCipherFloatArray(double* arr, int clength, double q);
extern double* NanPercentileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* NanPercentileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* NanPercentileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* QuantileCipherFloatArray(double* arr, int clength, double q);
extern double* QuantileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* QuantileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* QuantileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* NanQuantileCipherFloatArray(double* arr, int clength, double q);
extern double* NanQuantileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* NanQuantileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* NanQuantileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern double* MedianCipherFloatArray(double* arr, int clength);
extern double* MedianCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MedianCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* MedianCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanMedianCipherFloatArray(double* arr, int clength);
extern double* NanMedianCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanMedianCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* NanMedianCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* AverageCipherFloatArray(double* arr1, double* arr2, int clength);
extern double* AverageCipherFloatArrayArrayAxisNone(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* AverageCipherFloatArrayArrayAxis0(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* AverageCipherFloatArrayArrayAxis1(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* AverageCipherFloatArrayDouble(double* arr1, double* arr2, int clength1, int clength2);
extern double* AverageCipherFloatArrayArrayDoubleAxisNone(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern double* AverageCipherFloatArrayArrayDoubleAxis0(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern double* AverageCipherFloatArrayArrayDoubleAxis1(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern double* StdCipherFloatArray(double* arr, int clenght, int ddof);
extern double* StdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* StdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* StdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* NanStdCipherFloatArray(double* arr, int clenght, int ddof);
extern double* NanStdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* NanStdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* NanStdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* VarCipherFloatArray(double* arr, int clength, int ddof);
extern double* VarCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* VarCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* VarCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* NanVarCipherFloatArray(double* arr, int clength, int ddof);
extern double* NanVarCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* NanVarCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* NanVarCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern double* CorrcoefCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CorrelateCipherFloatArrayFull(double* arr1, double* arr2, int clength1, int clength2);
extern double* CorrelateCipherFloatArraySame(double* arr1, double* arr2, int clength1, int clength2);
extern double* CorrelateCipherFloatArrayValid(double* arr1, double* arr2, int clength1, int clength2);
extern double* CovCipherFloatArrayWithOneInput(double* arr, int clength);
extern double* CovCipherFloatArrayWithTwoInput(double* arr1, double* arr2, int clength, int outputEncryptType);
extern double* CovCipherFloat2dArrayWithOneInput(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* CovCipherFloat2dArrayWithTwoInput(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern int* DigitizeCipherFloatArrayFalse(double* arr1, double* arr2, int clength1, int clength2);
extern int* DigitizeCipherFloatArrayArrayFalse(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern int* DigitizeCipherFloatArrayTrue(double* arr1, double* arr2, int clength1, int clength2);
extern int* DigitizeCipherFloatArrayArrayTrue(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern _Bool IsCloseCipherFloat(double* arr1, double* arr2, int clength, double rtol, double atol);
extern _Bool* IsCloseCipherFloatArray(double* arr1, double* arr2, int clength, double rtol, double atol);
extern _Bool* IsCloseCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, double rtol, double atol, _Bool parallel);
extern double* ExpitCipherFloat(double* arr, int clength);
extern double* ExpitCipherFloatArray(double* arr, int clength);
extern double* ExpitCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* OrderCipherFloatArray(double* arr, int clength);
extern double* OrderCipherFloatArrayDecrement(double* arr, int clength);
extern double* OrderCipherFloatArrayArrayOneDecrement(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* OrderCipherFloatArrayArrayOne(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* OrderCipherFloatArrayArrayZeroDecrement(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* OrderCipherFloatArrayArrayZero(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double MapCipherFloat2Float64(double* arr, int clength);
extern double* MapCipherFloatArray2Float64Array(double* arr, int clength);
extern double* MapFloat2CipherFloat(double a);
extern double* MapFloatArray2CipherFloatArray(double* arr, int clength);
extern double* PowerFloatCipherFloat(double* arr, int clength, double m);
extern double* PowerFloatCipherFloatArray(double* arr, int clength, double m);
extern double* PowerFloatCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern double* FlipCipherFloatArray(double* arr, int clength);
extern double* FlipCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* FlipCipherFloatArrayArrayZero(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* FlipCipherFloatArrayArrayOne(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* WhereCipherFloatArray(_Bool* condit, int clength1, double* arr1, double* arr2, int clength2);
extern double* WhereCipherFloatArrayArray(_Bool* condit, int clength1, int clength2, double* arr1, double* arr2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern double* InvCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern double* VanderCipherFloatArray(double* arr, int clength, int degree, int outputEncrytType);
extern double* PolyfitCipherFloatArray(double* arr1, double* arr2, int clength, int degree, _Bool parallel);
extern int* ArgSortCipherFloatArray(double* arr, int clength);
extern int* ArgSortCipherFloatArrayDecrement(double* arr, int clength);
extern int* ArgSortCipherFloatArrayArrayOne(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int* ArgSortCipherFloatArrayArrayOneDecrement(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int* ArgSortCipherFloatArrayArrayZero(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern int* ArgSortCipherFloatArrayArrayZeroDecrement(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* TransposeCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern double* InsertCipherArrayArray(double* arr1, int clength1, int clength2, int encryptType, int outputEncryptType, double* arr2, int clength3, int index);
extern double* TransEncType(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern double* ReshapeCipherFloatArray(double* arr, int clength, int shape1, int shape2, int outputEncryptType);
extern double* ReshapeCipherFloatArrayArray(double* arr, int* shape, int clength1, int clength2, int shapeLength, int encryptType, int outputEncryptType, _Bool parallel);
extern double* LinspaceCipherFloat(double* arr1, double* arr2, int clength, int num, _Bool endpoint);

#ifdef __cplusplus
}
#endif
