/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "export_float.go"
 #include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void _init_dict(GoString dictFilePath, GoString userFilePath);
extern __declspec(dllexport) void FreeMemory(double* ptr);
extern __declspec(dllexport) void FreeIntPtr(int* ptr);
extern __declspec(dllexport) void FreeBoolPtr(_Bool* ptr);
extern __declspec(dllexport) void arrtest1(double* arr, int clength);
extern __declspec(dllexport) void arrtest2(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* GetEmptyCipherFloatArray();
extern __declspec(dllexport) double* GetEmptyCipherFloat();
extern __declspec(dllexport) double* AddCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* AddCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* SubCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* SubCipherFloatDouble(double* arr, int clength, GoFloat64 m);
extern __declspec(dllexport) double* SubCipherFloatDoubleRight(double* arr, int clength, GoFloat64 m);
extern __declspec(dllexport) double* MulCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* MulCipherFloatDouble(double* arr1, int clength, double m);
extern __declspec(dllexport) double* DivCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* DivCipherFloatDouble(double* arr1, int clength, double m);
extern __declspec(dllexport) double* DivCipherFloatDoubleRight(double* arr, int clength, GoFloat64 m);
extern __declspec(dllexport) double* InversCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) int Compare2CipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* AddCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* AddCipherFloatArrayDouble(double* arr, int clength, GoFloat64 m);
extern __declspec(dllexport) double* AddCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* AddCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SubCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* SubCipherFloatArrayDouble(double* arr, int clength, GoFloat64 m);
extern __declspec(dllexport) double* SubCipherFloatArrayDoubleRight(double* arr, int clength, GoFloat64 m);
extern __declspec(dllexport) double* SubCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SubCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SubCipherFloatArrayArrayDoubleRight(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MulCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* MulCipherFloatArrayDouble(double* arr1, int clength, double m);
extern __declspec(dllexport) double* MulCipherFloatArrayDoubleArray(double* arr1, int clength1, double* arr2, int clength2);
extern __declspec(dllexport) double* MulCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MulCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* DivCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* DivCipherFloatArrayDouble(double* arr1, int clength, double m);
extern __declspec(dllexport) double* DivCipherFloatArrayDoubleRight(double* arr, int clength, double m);
extern __declspec(dllexport) double* DivCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* DivCipherFloatArrayArrayDouble(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* DivCipherFloatArrayArrayDoubleRight(double* arr, double m, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* InversCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* ABSCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ABSCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ABSCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* PowCipherFloat(double* arr, int clength, int n);
extern __declspec(dllexport) double* PowCipherFloatArray(double* arr, int clength, int n);
extern __declspec(dllexport) double* PowCipherFloatArrayArray(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* PowCipherFloat_FractionOrder(double* arr, int clength, int n, int m);
extern __declspec(dllexport) double* PowCipherFloatArray_FractionOrder(double* arr, int clength, int n, int m);
extern __declspec(dllexport) double* PowCipherFloatArrayArray_FractionOrder(double* arr, int clength1, int clength2, int n, int m, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) int* Compare2CipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) int* Compare2CipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool EqualCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool EqualCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* EqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool* EqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* EqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool* EqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern __declspec(dllexport) _Bool NotEqualCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool NotEqualCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* NotEqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool* NotEqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* NotEqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool* NotEqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern __declspec(dllexport) _Bool GreaterEqualCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool GreaterEqualCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* GreaterEqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool* GreaterEqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* GreaterEqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool* GreaterEqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern __declspec(dllexport) _Bool LessEqualCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool LessEqualCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* LessEqualCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool* LessEqualCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* LessEqualCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool* LessEqualCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern __declspec(dllexport) _Bool GreaterCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool GreaterCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* GreaterCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool* GreaterCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* GreaterCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool* GreaterCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern __declspec(dllexport) _Bool LessCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool LessCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* LessCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) _Bool* LessCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) _Bool* LessCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool* LessCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, double m, _Bool parallel);
extern __declspec(dllexport) double* SqrtCipherFloat(double* arr1, int clength);
extern __declspec(dllexport) double* SqrtCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* SqrtCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* HypotFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* HypotFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* HypotCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* Arctan2Float(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* Arctan2CipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* Arctan2CipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* Rad2degFloat(double* arr, int clength);
extern __declspec(dllexport) double* Rad2degFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* Rad2degCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* Deg2radFloat(double* arr, int clength);
extern __declspec(dllexport) double* Deg2radFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* Deg2radCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* DegreesFloat(double* arr, int clength);
extern __declspec(dllexport) double* DegreesFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* DegreesCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* RadiansFloat(double* arr, int clength);
extern __declspec(dllexport) double* RadiansFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* RadiansCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* RoundCipherFloat(double* arr, int clength, int n, int m);
extern __declspec(dllexport) double* RoundCipherFloatArray(double* arr, int clength, int n, int m);
extern __declspec(dllexport) double* RoundCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryType, int n, int m, _Bool parallel);
extern __declspec(dllexport) double* RoundingNCipherFloat(double* arr, int clength, int n);
extern __declspec(dllexport) double* RoundingNCipherFloatArray(double* arr, int clength, int n);
extern __declspec(dllexport) double* RoundingNCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, int n, _Bool parallel);
extern __declspec(dllexport) double* ReciprocalFloat(double* arr, int clength);
extern __declspec(dllexport) double* ReciprocalFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ReciprocalFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* PositiveFloat(double* arr, int clength);
extern __declspec(dllexport) double* PositiveFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* PositiveFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* NegativeFloat(double* arr, int clength);
extern __declspec(dllexport) double* NegativeFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NegativeFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CbrtFloat(double* arr, int clength);
extern __declspec(dllexport) double* CbrtCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* CbrtCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SquareFloat(double* arr, int clength);
extern __declspec(dllexport) double* SquareFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* SquareFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* HeavisideFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* HeavisideCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* HeavisideCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SinCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* SinCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* SinCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CosCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* CosCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* CosCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CosineCipherFloatDiscreteArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* TanCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* TanCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* TanCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ArcsinCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ArcsinCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ArcsinCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ArccosCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ArccosCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ArccosCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ArctanCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ArctanCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ArctanCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SinhCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* SinhCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* SinhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CoshCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* CoshCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* CoshCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* TanhCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* TanhCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* TanhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ArcsinhCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ArcsinhCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ArcsinhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ArccoshCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ArccoshCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ArccoshCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ArctanhCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ArctanhCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ArctanhCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SumFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* SumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* SumCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* SumCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanSumFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NanSumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* NanSumFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType);
extern __declspec(dllexport) double* NanSumFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType);
extern __declspec(dllexport) double* Unwrap(double* arr, int clength, double discont, double period);
extern __declspec(dllexport) double* UnwrapCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double discont, double period, _Bool parallel);
extern __declspec(dllexport) double* UnwrapCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double discont, double period, _Bool parallel);
extern __declspec(dllexport) double* FixCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* FixCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* FixCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* FloorCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* FloorCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* FloorCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CeilCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* CeilCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* CeilCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* DecimalCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* DecimalCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* DecimalCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ProdCipherArray(double* arr, int clength);
extern __declspec(dllexport) double* ProdCipherArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* ProdCipherArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* ProdCipherArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanProdCipherArray(double* arr, int clength);
extern __declspec(dllexport) double* NanProdCipherArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* NanProdCipherArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanProdCipherArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* CumProdCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* CumProdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern __declspec(dllexport) double* CumProdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* CumProdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* NanCumProdCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NanCumProdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern __declspec(dllexport) double* NanCumProdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* NanCumProdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* CumSumCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* CumSumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern __declspec(dllexport) double* CumSumCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* CumSumCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* NanCumSumCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NanCumSumCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType);
extern __declspec(dllexport) double* NanCumSumCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* NanCumSumCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* DiffCipherFloatArray(double* arr, int clength, int n);
extern __declspec(dllexport) double* DiffCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* DiffCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* Ediff1dCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType);
extern __declspec(dllexport) double* GradientCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* GradientCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* GradientCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* GradientCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CrossCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* CrossCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int axis1, int axis2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* TrapzCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* TrapzCipherFloatArrayDx(double* arr, int clength, double dx);
extern __declspec(dllexport) double* TrapzCipherFloatArrayArrayAxis0(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* TrapzCipherFloatArrayArrayAxis1(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* TrapzCipherFloatArrayArrayDxAxis0(double* arr, int clength1, int clength2, int encryptType, double dx, _Bool parallel);
extern __declspec(dllexport) double* TrapzCipherFloatArrayArrayDxAxis1(double* arr, int clength1, int clength2, int encryptType, double dx, _Bool parallel);
extern __declspec(dllexport) double* NormNCipherFloatArray(double* arr, int clength, int n);
extern __declspec(dllexport) double* NormPosInfCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NormNegInfCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) int NormZeroCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* MinCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* MinCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MinCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MinCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MaxCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* MaxCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MaxCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MaxCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MeanCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* MeanCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MeanCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MeanCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanMeanCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NanMeanCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanMeanCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanMeanCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int ArgMinCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) int ArgMinCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* ArgMinCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* ArgMinCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int ArgMaxCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) int ArgMaxCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* ArgMaxCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* ArgMaxCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* OnesCipherFloat();
extern __declspec(dllexport) double* OnesCipherFloatArray(int n);
extern __declspec(dllexport) double* OnesCipherFloatArrayArray(int m, int n, int outputEncryptType);
extern __declspec(dllexport) double* ZerosCipherFloat();
extern __declspec(dllexport) double* ZerosCipherFloatArray(int n);
extern __declspec(dllexport) double* ZerosCipherFloatArrayArray(int m, int n, int outputEncryptType);
extern __declspec(dllexport) double* PlainArrayToCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* Plain2DArrayToCipherFloat2DArray(double* arr, int clength1, int clength2, int outputEncryptType);
extern __declspec(dllexport) double* LogCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* LogCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* LogCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* Log10CipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* Log10CipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* Log10CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* Log2CipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* Log2CipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* Log2CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ExpCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ExpCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ExpCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* Expm1CipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* Expm1CipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* Expm1CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* Exp2CipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* Exp2CipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* Exp2CipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CipherFloatArrayAppendCipherFloat(double* arr, int clength1, double* c, int clength2);
extern __declspec(dllexport) double* CipherFloatArrayAppendCipherFloatArray(double* arr1, int clength1, double* arr2, int clength2);
extern __declspec(dllexport) double* CipherFloatArrayAppendCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* CipherFloatArrayArrayAppendCipherFloat(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* CipherFloatArrayArrayAppendCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* CipherFloatArrayArrayAppendCipherFloatArrayArrayAxisNone(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* CipherFloatArrayArrayAppendCipherFloatArrayArrayAxis0(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CipherFloatArrayArrayAppendCipherFloatArrayArrayAxis1(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* FloorDivideCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FloorDivideCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* FloorDivideCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FloorDivideCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* FloorDivideCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* FloorDivideCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern __declspec(dllexport) double* FModCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FModCipherFloatDouble(double* arr, int clength, GoFloat64 m);
extern __declspec(dllexport) double* FModCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FModCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* FModCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* FModCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern __declspec(dllexport) double* ModCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* ModCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* ModCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* ModCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* ModCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ModCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern __declspec(dllexport) double* ConvolveCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* ConvolveCipherFloatArraySame(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* ConvolveCipherFloatArrayValid(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* ClipCipherFloat(double* arr1, double* arr2, double* arr3, int clength);
extern __declspec(dllexport) double* ClipCipherFloatArray(double* arr1, double* arr2, double* arr3, int clength);
extern __declspec(dllexport) double* ClipCipherFloatArrayArray(double* arr1, double* arr2, double* arr3, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* SignCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* SignCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* SignCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MaximumCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* MaximumCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* MaximumCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MinimumCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* MinimumCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* MinimumCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* FMaxCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FMaxCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FMaxCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* FMinCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FMinCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* FMinCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* ModFCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ModFCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ModFCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* DivModCipherFloat(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* DivModCipherFloatDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* DivModCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* DivModCipherFloatArrayDouble(double* arr, int clength, double m);
extern __declspec(dllexport) double* DivModCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* DivModCipherFloatArrayArrayDouble(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern __declspec(dllexport) double* InterpCipherFloat(double* c1, double* xp, double* fp, double* left, double* right, int clength1, int clength2);
extern __declspec(dllexport) double* InterpCipherFloatArray(double* c1, double* xp, double* fp, double* left, double* right, int clength1, int clength2, int clength3);
extern __declspec(dllexport) double* InterpCipherFloatArrayArray(double* c1, double* xp, double* fp, double* left, double* right, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* NanToNumCipherFloat(double* arr, double* nan, double* posinf, double* neginf, int clength);
extern __declspec(dllexport) double* NanToNumCipherFloatArray(double* arr, int clength1, double* nan, double* posinf, double* neginf, int clength2);
extern __declspec(dllexport) double* NanToNumCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double* nan, double* posinf, double* neginf, int clength3);
extern __declspec(dllexport) double* DotCipherFloatArray2DWith1D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* InnerCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* InnerCipherFloat2DWith1D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* InnerCipherFloat2DWith2D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* OuterCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MatmulCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MatmulCipherFloatArrayFastCol(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MatMulCipherFloat1DWith2D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType);
extern __declspec(dllexport) double* MatMulCipherFloat2DWith1D(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* MatrixPowerCipherFloatArray(double* arr, int clength1, int clength2, int n, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* GetEyeCipherFloatArrayArray(int n, int outputEncryptType);
extern __declspec(dllexport) double* KronCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* TraceCipherFloatArray(double* arr, int clength1, int clength2, int encrytType, _Bool parallel);
extern __declspec(dllexport) double* DetCipherFloatArrayArray(double* arr, int clength1, int clength2, int encrytType);
extern __declspec(dllexport) double* NanminCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NanminCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanminCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanminCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanmaxCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NanmaxCipherFloatArrayArrayAxisNone(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanmaxCipherFloatArrayArrayAxis0(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanmaxCipherFloatArrayArrayAxis1(double* arr1, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* PtpCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* PtpCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* PtpCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* PtpCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* PercentileCipherFloatArray(double* arr, int clength, double q);
extern __declspec(dllexport) double* PercentileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* PercentileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* PercentileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* NanPercentileCipherFloatArray(double* arr, int clength, double q);
extern __declspec(dllexport) double* NanPercentileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* NanPercentileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* NanPercentileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* QuantileCipherFloatArray(double* arr, int clength, double q);
extern __declspec(dllexport) double* QuantileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* QuantileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* QuantileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* NanQuantileCipherFloatArray(double* arr, int clength, double q);
extern __declspec(dllexport) double* NanQuantileCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* NanQuantileCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* NanQuantileCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, double q, _Bool parallel);
extern __declspec(dllexport) double* MedianCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* MedianCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MedianCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* MedianCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanMedianCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* NanMedianCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanMedianCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* NanMedianCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* AverageCipherFloatArray(double* arr1, double* arr2, int clength);
extern __declspec(dllexport) double* AverageCipherFloatArrayArrayAxisNone(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* AverageCipherFloatArrayArrayAxis0(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* AverageCipherFloatArrayArrayAxis1(double* arr1, double* arr2, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* AverageCipherFloatArrayDouble(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* AverageCipherFloatArrayArrayDoubleAxisNone(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* AverageCipherFloatArrayArrayDoubleAxis0(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* AverageCipherFloatArrayArrayDoubleAxis1(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* StdCipherFloatArray(double* arr, int clenght, int ddof);
extern __declspec(dllexport) double* StdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* StdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* StdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* NanStdCipherFloatArray(double* arr, int clenght, int ddof);
extern __declspec(dllexport) double* NanStdCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* NanStdCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* NanStdCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* VarCipherFloatArray(double* arr, int clength, int ddof);
extern __declspec(dllexport) double* VarCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* VarCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* VarCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* NanVarCipherFloatArray(double* arr, int clength, int ddof);
extern __declspec(dllexport) double* NanVarCipherFloatArrayArrayAxisNone(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* NanVarCipherFloatArrayArrayAxis0(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* NanVarCipherFloatArrayArrayAxis1(double* arr, int clength1, int clength2, int encryptType, int ddof, _Bool parallel);
extern __declspec(dllexport) double* CorrcoefCipherFloatArray(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CorrelateCipherFloatArrayFull(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* CorrelateCipherFloatArraySame(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* CorrelateCipherFloatArrayValid(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) double* CovCipherFloatArrayWithOneInput(double* arr, int clength);
extern __declspec(dllexport) double* CovCipherFloatArrayWithTwoInput(double* arr1, double* arr2, int clength, int outputEncryptType);
extern __declspec(dllexport) double* CovCipherFloat2dArrayWithOneInput(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* CovCipherFloat2dArrayWithTwoInput(double* arr1, double* arr2, int clength1, int clength2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) int* DigitizeCipherFloatArrayFalse(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) int* DigitizeCipherFloatArrayArrayFalse(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* DigitizeCipherFloatArrayTrue(double* arr1, double* arr2, int clength1, int clength2);
extern __declspec(dllexport) int* DigitizeCipherFloatArrayArrayTrue(double* arr1, double* arr2, int clength1, int clength2, int clength3, int encryptType, _Bool parallel);
extern __declspec(dllexport) _Bool IsCloseCipherFloat(double* arr1, double* arr2, int clength, double rtol, double atol);
extern __declspec(dllexport) _Bool* IsCloseCipherFloatArray(double* arr1, double* arr2, int clength, double rtol, double atol);
extern __declspec(dllexport) _Bool* IsCloseCipherFloatArrayArray(double* arr1, double* arr2, int clength1, int clength2, int encryptType, double rtol, double atol, _Bool parallel);
extern __declspec(dllexport) double* ExpitCipherFloat(double* arr, int clength);
extern __declspec(dllexport) double* ExpitCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* ExpitCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* OrderCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* OrderCipherFloatArrayDecrement(double* arr, int clength);
extern __declspec(dllexport) double* OrderCipherFloatArrayArrayOneDecrement(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* OrderCipherFloatArrayArrayOne(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* OrderCipherFloatArrayArrayZeroDecrement(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* OrderCipherFloatArrayArrayZero(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double MapCipherFloat2Float64(double* arr, int clength);
extern __declspec(dllexport) double* MapCipherFloatArray2Float64Array(double* arr, int clength);
extern __declspec(dllexport) double* MapFloat2CipherFloat(double a);
extern __declspec(dllexport) double* MapFloatArray2CipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* PowerFloatCipherFloat(double* arr, int clength, double m);
extern __declspec(dllexport) double* PowerFloatCipherFloatArray(double* arr, int clength, double m);
extern __declspec(dllexport) double* PowerFloatCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, double m, _Bool parallel);
extern __declspec(dllexport) double* FlipCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) double* FlipCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* FlipCipherFloatArrayArrayZero(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* FlipCipherFloatArrayArrayOne(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* WhereCipherFloatArray(_Bool* condit, int clength1, double* arr1, double* arr2, int clength2);
extern __declspec(dllexport) double* WhereCipherFloatArrayArray(_Bool* condit, int clength1, int clength2, double* arr1, double* arr2, int clength3, int clength4, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* InvCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType);
extern __declspec(dllexport) double* VanderCipherFloatArray(double* arr, int clength, int degree, int outputEncrytType);
extern __declspec(dllexport) double* PolyfitCipherFloatArray(double* arr1, double* arr2, int clength, int degree, _Bool parallel);
extern __declspec(dllexport) int* ArgSortCipherFloatArray(double* arr, int clength);
extern __declspec(dllexport) int* ArgSortCipherFloatArrayDecrement(double* arr, int clength);
extern __declspec(dllexport) int* ArgSortCipherFloatArrayArrayOne(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* ArgSortCipherFloatArrayArrayOneDecrement(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* ArgSortCipherFloatArrayArrayZero(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) int* ArgSortCipherFloatArrayArrayZeroDecrement(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* TransposeCipherFloatArrayArray(double* arr, int clength1, int clength2, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* InsertCipherArrayArray(double* arr1, int clength1, int clength2, int encryptType, int outputEncryptType, double* arr2, int clength3, int index);
extern __declspec(dllexport) double* TransEncType(double* arr, int clength1, int clength2, int encryptType, _Bool parallel);
extern __declspec(dllexport) double* ReshapeCipherFloatArray(double* arr, int clength, int shape1, int shape2, int outputEncryptType);
extern __declspec(dllexport) double* ReshapeCipherFloatArrayArray(double* arr, int* shape, int clength1, int clength2, int shapeLength, int encryptType, int outputEncryptType, _Bool parallel);
extern __declspec(dllexport) double* LinspaceCipherFloat(double* arr1, double* arr2, int clength, int num, _Bool endpoint);

#ifdef __cplusplus
}
#endif
